// This files contains settings for development
// Build version of config.js is generated by ant scripts.
// See build.xml for more details.


var criterion = criterion || {};

criterion.locales = [];

criterion.AUTH_URL = 'https://turing-login.criterionhcm.com';
criterion.appName = 'admin';
criterion.support = {};
criterion.support.phone = '+1 203 703 9000';
criterion.support.email = 'support@criterionhcm.com';

if (location.href.indexOf('siesta') !== -1) {
    console && console.log('Siesta time!');
    criterion.TEST_MODE = true;
    // criterion.API_TOKEN and criterion.API_TENANT_ID are not used anymore. See  https://perfecthr.atlassian.net/browse/CR-8707
    criterion.API_TOKEN = '4w50bx1HMl795qLCKxfcRfSLbyOtLmblbeDl0TWzfuk=';
    criterion.API_TENANT_ID = '999';
}

if (location.href.indexOf('siestaUnit') !== -1) {
    criterion.UNIT_TEST_MODE = true;
}