// This files contains settings for development
// Build version of config.js is generated by ant scripts.
// See build.xml for more details.

var criterion = criterion || {},
    LOGIN_MODES = {// >0 (1) for native builds, 2 for GlobalLogin
        web : 0,
        mobile : 1,
        api : 2
    };

criterion.locales = [];

function merge_objects(object1, object2) {
    var ret_object = {};
    for (var attrname in object1) {
        ret_object[attrname] = object1[attrname];
    }
    for (var attrname in object2) {
        ret_object[attrname] = object2[attrname];
    }
    return ret_object;
}

criterion = merge_objects(criterion, {
    AUTH_URL : 'https://turing-login.criterionhcm.com',
    AUTH : {},
    DIRECT_AUTH : LOGIN_MODES.web,
    appName : 'ess',
    support : {},
    buildAuthCfg : function() {
        criterion.AUTH = merge_objects(criterion.AUTH, {
            DIRECT_AUTH_LOGIN : criterion.AUTH_URL + '/direct/login',
            DIRECT_AUTH_INFO : criterion.AUTH_URL + '/direct/userInfo',
            DIRECT_AUTH_FORGOT : criterion.AUTH_URL + '/direct/forgot',
            DIRECT_AUTH_TENANT : criterion.AUTH_URL + '/direct/tenant',
            DIRECT_AUTH_2FA : criterion.AUTH_URL + '/direct/2fa',
            DIRECT_AUTH_SET_PASSWORD : criterion.AUTH_URL + '/direct/setPassword',
            DIRECT_AUTH_AZURE : criterion.AUTH_URL + '/external/auth/azure/mobile',
            GLOBAL_AUTH_INFO : criterion.AUTH_URL + '/userInfo',
            TENANT_STYLE : criterion.AUTH_URL + '/tenant/styles/',
            BIOMETRIC_LOGIN : criterion.AUTH_URL + '/direct/biometricLogin'
        });
    }
});

criterion.buildAuthCfg();

if (location.href.indexOf('siesta') !== -1) {
    console && console.log('Siesta time!');
    criterion.TEST_MODE = true;
    // criterion.API_TOKEN and criterion.API_TENANT_ID are not used anymore. See https://perfecthr.atlassian.net/browse/CR-8707
    criterion.API_TOKEN = 'eI9A9AvnffskgD/56AtHfncZn1ikdGrn9nDbFX1V4oCSckmLvqz2eaxOsS8Yo+nM	';
    criterion.API_TENANT_ID = '2';
}

if (location.href.indexOf('siestaUnit') !== -1) {
    criterion.UNIT_TEST_MODE = true;
}
